# baseURL: https://letscompost.com
baseURL: "https://compostclub.site"
languageCode: en-us
title: Compost Club
theme: "fresh"

params:
  hero:
    tagline: Compost Club
    subTagline: On demand composting. Coming soon to Adelaide.
    buttonText: See Pricing
    buttonUrl: /#pricing
    image: illustrations/man_plant.png
    # bottomIcons:
    # - logos/clients/systek.svg
    # - logos/clients/tribe.svg
    # - logos/clients/kromo.svg
    # - logos/clients/infinite.svg
    # - logos/clients/gutwork.svg
  navbar:
    buttonText: Join the list!
    buttonUrl: /#pricing
    logo:
      src: logos/logo_compostclub.png
      alt: Main navbar logo
    links:
    - text: Features
      url: /#pricing
    - text: Pricing
      url: /#pricing
    # - text: Dropdown
    #   dropdown: true
    #   links:
    #   - Dropdown item 1
    #   - Dropdown item 2
    #   - Dropdown item 3
  features:
    # TODO: AB test pricing
    id: pricing
    tagline: You know you should be composting.
    subTagline: Let us take care of it for you.
    panels:
    - title: Do nothing
      image: illustrations/dead_fish.png
      text: Go on. Sit back and watch the world burn.
      button:
        id: dummyButton
        text: $0
        url: https://lewisdaly.typeform.com/to/MwBWCr
      delay: 1
    - title: Fortnightly
      image: illustrations/pot_plant.png
      text: Not too much to compost, but it's still important.
      button:
        id: opt1Button
        text: $10 Monthly
        url: https://lewisdaly.typeform.com/to/MwBWCr
      delay: 2
    - title: Weekly
      image: illustrations/trees.png
      text: We pick up your compost once a week. Great for families.
      button:
        id: opt2Button
        text: $18 Monthly
        url: /
        # url: https://lewisdaly.typeform.com/to/MwBWCr
      delay: 3
  sellingPoints:
    tagline: Here's how it works
    points:
    - title: Step 1
      description: You sign up for Compost Club, we give you a bucket to use for your compost.
      icon: sheep
    - title: Step 2
      description: On your designated pick up day, leave it out on the curb from 6:30am.
      icon: doc_sync
    - title: Step 3
      description: We swap your bucket over for a new one. No need to clean up the mess.
      icon: mobile-feed
  platform:
    image: /hands.jpg
    tagline: Support a worthy cause
    subTagline: Not only do you get to do the right thing with your waste, but 100% of our profits go towards supporting sustainable agriculture in low income countries.
    buttonText: Learn more about our work
    buttonUrl: "https://vesselstech.com"
  # clients:
  #   tagline: Our Clients love us!
  #   subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clientExamples:
  #   - name: Irma Walters
  #     position: Accountant
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     image: 1.png
  #   - name: John Bradley
  #     position: Financial Analyst
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     image: 2.png
  #   - name: Gary Blackman
  #     position: HR Manager
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     image: 3.png
  # contact:
  #   tagline: Want to learn more? Drop us a line or two!
  footer:
    image: /logo_compostclub_light.png
    columns:
    - title: About Us
      links:
      - name: Vessels Tech
        url: "https://vesselstech.com"
      # - name: Why choose our Product?
      #   url: "#"
      # - name: Compare features
      #   url: "#"
      # - name: Our Roadmap
      #   url: "#"
      # - name: Request features
      #   url: "#"
    # - title: Docs
    #   links:
    #   - name: Get Started
    #     url: "#"
    #   - name: User guides
    #     url: "#"
    #   - name: Admin guide
    #     url: "#"
    #   - name: Developers
    #     url: "#"
    - title: Blogroll
      links:
      - name: Latest News
        url: "https://medium.com/vessels"
    followUs:
    - icon: twitter
      url: "https://twitter.com/lewdaly"
    - icon: globe
      url: "mailto:lewis@vesselstech.com"
url: "#"