export GOOGLE_ANALYTICS_TRACKING=""
export PROTOCOL="https"
export BASE_URL="compostclub.site"
export SITE_ID="compostclub"
export SITE_NAME="Compost Club"
export S3_BUCKET_NAME="compostclub.site"
export ACM_CERTIFICATE_ARN="???"
export STACK_NAME="public-compostclub"