export GOOGLE_ANALYTICS_TRACKING=""
export PROTOCOL="https"
export BASE_URL="letscompost.club"
export SITE_ID="letscompost"
export SITE_NAME="Let's Compost"
export S3_BUCKET_NAME="letscompost.club"
export STACK_NAME="public-letscompost"