export GOOGLE_ANALYTICS_TRACKING=""
export PROTOCOL="http"
export BASE_URL="localhost:1313"
export SITE_ID="lets_compost"
export SITE_NAME="Let's Compost"
export S3_BUCKET_NAME="letscompost.club"
export STACK_NAME="public-letscompost"
export ACM_CERTIFICATE_ARN="nothing"