export GOOGLE_ANALYTICS_TRACKING=""
export PROTOCOL="https"
export BASE_URL="compostable.site"
export SITE_ID="compostable"
export SITE_NAME="Compostable"
export S3_BUCKET_NAME="compostable.site"
export STACK_NAME="public-compostable"
export ACM_CERTIFICATE_ARN="arn:aws:acm:us-east-1:745457803371:certificate/ff73b110-7f34-45f5-86ab-de96c46962fa"