export GOOGLE_ANALYTICS_TRACKING=""
export PROTOCOL="https"
export BASE_URL="compostable.site"
export SITE_ID="compostable"
export SITE_NAME="Compostable"
export S3_BUCKET_NAME="compostable.site"
export STACK_NAME="public-compostable"